package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class GrupoAsigIT{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
  
  @Before
  public void setUp() {
	BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Ignore
  public void grupoAsigITLista() {
    driver.get("http://localhost:8080/ProyectoSII-war/");
    driver.manage().window().setSize(new Dimension(767, 702));
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.xpath("//tbody[@id=\'gruposAsig:dataTableGrupAsig_data\']/tr/td")).click();
    assertThat(driver.findElement(By.cssSelector(".ui-widget-content:nth-child(1) > td:nth-child(1)")).getText(), is("1ºA"));
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:nombreAsig")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:nombreAsig")).getText(), is("Calculo"));
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:cursoAcademic")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:cursoAcademic")).getText(), is("20/21"));
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("true"));
  }
  @Test
  @Ignore
  public void editarGrupoAsigIT() {
    driver.get("http://localhost:8080/ProyectoSII-war/");
    driver.manage().window().setSize(new Dimension(767, 704));
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("true"));
    driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:seleccionEditar\']/a/span")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:modelInput")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:modelInput")).sendKeys("false");
    driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:seleccionEditar\']/a[2]")).click();
    driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:j_idt11\']/div")).click();
    assertThat(driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:j_idt11\']/div")).getText(), is("false"));
  }
  
  @Test
  @Ignore
  public void buscadorPorAsignatura() {
    driver.get("http://localhost:8080/ProyectoSII-war/");
    driver.manage().window().setSize(new Dimension(767, 706));
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.xpath("//tbody[@id=\'gruposAsig:dataTableGrupAsig_data\']/tr/td[2]")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:nombreAsig")).getText(), is("Cálculo para la Computación"));
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:j_idt8:filter")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:j_idt8:filter")).sendKeys("Cálculo");
  }
}
