package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import es.uma.informatica.sii.anotaciones.Requisitos;

public class PruebaExpedienteIT {
	
	  private WebDriver driver;
	  private Map<String, Object> vars;
	  JavascriptExecutor js;
	  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
	  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
	  
	  @Before
	  public void setUp() {
		BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
	    driver = new FirefoxDriver();
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
	    driver.get("http://localhost:8080/ProyectoSII-war/");
	  }
	  @After
	  public void tearDown() {
	    driver.quit();
	  }
	  
	  @Requisitos({"RF-08"})
	  @Test
	  public void buscarExpedienteTest() {
		  for(int i=0; i<=2;i++){
			  try{
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(825, 726));
				  driver.findElement(By.id("formIndex:botonExpedientes")).click();
				  driver.findElement(By.id("Expedientes:TablaExpedientes:globalFilter")).click();
				  driver.findElement(By.id("Expedientes:TablaExpedientes:globalFilter")).sendKeys("4");
				  driver.findElement(By.cssSelector("td:nth-child(1)")).click();
				  assertThat(driver.findElement(By.id("Expedientes:TablaExpedientes:0:SalidaNumexpediente")).getText(), is("4"));


				  break;
			  }
			  catch(Exception e){

			  }
		  }

	  }
	  
	  
	  @Requisitos({"RF-08"})
	  @Test
	  public void modificarExpedientesTest() {
		  for(int i=0; i<=2;i++){
			  try{
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(825, 725));
				  driver.findElement(By.id("formIndex:botonExpedientes")).click();
				  driver.findElement(By.id("Expedientes:TablaExpedientes:0:BotonModificar")).click();
				  driver.findElement(By.id("expediente:credito_ob")).click();
				  driver.findElement(By.id("expediente:credito_ob")).sendKeys("1");
				  driver.findElement(By.id("expediente:BotonAccion")).click();
				  driver.findElement(By.id("expediente:BotonCancelar")).click();
				  driver.findElement(By.id("Expedientes:TablaExpedientes:0:SalidaCreditosob")).click();
				  assertThat(driver.findElement(By.id("Expedientes:TablaExpedientes:0:SalidaCreditosob")).getText(), is("1"));


				  break;
			  }
			  catch(Exception e){

			  }
		  }

	  }
	  
	  
	  @Requisitos({"RF-08"})
	  @Test
	  public void buscarExpedientesMalTest() {
		  
		  for(int i=0; i<=2;i++){
			  try{
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				    driver.manage().window().setSize(new Dimension(825, 727));
				    driver.findElement(By.id("formIndex:botonExpedientes")).click();
				    driver.findElement(By.id("Expedientes:TablaExpedientes:globalFilter")).click();
				    driver.findElement(By.id("Expedientes:TablaExpedientes:globalFilter")).sendKeys("ramon");
				    driver.findElement(By.cssSelector("td")).click();
				    assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ningun expediente con esos filtros"));


				  break;
			  }
			  catch(Exception e){

			  }
		  }
	    
	  }
	  
	  
	  
	  
	  

}
