package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import es.uma.informatica.sii.anotaciones.Requisitos;
public class PruebaGrupoAsigIT{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
  
  @Before
  public void setUp() {
	BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:8080/ProyectoSII-war/");
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Requisitos({"RF-13","RF-16"})
  @Test
  public void buscarGrupoPorAsignatura() {
	for(int i=0;i<=2;i++) {
		try {
			driver.get("http://localhost:8080/ProyectoSII-war/");
		    driver.manage().window().setSize(new Dimension(846, 715));
		    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
		    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:CNombreAsig:filter")).sendKeys("Calc");
		    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:nombreAsig")).getText(), is("Calculo"));
		    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:cursoAcademic")).getText(), is("20/21"));
		    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("true"));
		    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:grupo")).getText(), is("1ºA"));
		    break;
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
    
  }
  @Requisitos({"RF-16"})
  @Test
  public void editarGruporAsig() {
	for(int i=0;i<=2;i++) {
		try {
			driver.get("http://localhost:8080/ProyectoSII-war/");
		    driver.manage().window().setSize(new Dimension(1015, 719));
		    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
		    driver.findElement(By.cssSelector(".ui-icon-pencil")).click();
		    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:ofertaInput")).click();
		    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:ofertaInput")).sendKeys("false");
		    driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:seleccionEditar\']/a[2]/span")).click();
		    driver.findElement(By.xpath("//tbody[@id=\'gruposAsig:dataTableGrupAsig_data\']/tr/td[4]")).click();
		    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("false"));
		    break;
			
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
    
  }
  @Requisitos({"RF-16"})
  @Test
  public void eliminarGrupoAsig() {
	for(int i=0;i<=2;i++) {
		driver.get("http://localhost:8080/ProyectoSII-war/");
	    driver.manage().window().setSize(new Dimension(1015, 720));
	    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
	    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:BotonEliminar")).click();
	    assertThat(driver.findElement(By.xpath("//tbody[@id=\'gruposAsig:dataTableGrupAsig_data\']/tr/td")).getText(), is("Ningun grupo asignatura con esos filtros"));
	    break;
	}
    
  }
  @Requisitos({"RF-16"})
  @Test
  public void usoFiltrosGruposAsig() {
	for(int i=0;i<=2;i++) {
		try {
			driver.get("http://localhost:8080/ProyectoSII-war/");
		    driver.manage().window().setSize(new Dimension(1015, 729));
		    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:CGrupo:filter")).click();
		    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:CGrupo:filter")).sendKeys("1ºA");
		    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:grupo")).getText(), is("1ºA"));
		    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:CCursoAcademic:filter")).sendKeys("20/21");
		    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:cursoAcademic")).getText(), is("20/21"));
		    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:COfertada:filter")).sendKeys("true");
		    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("true"));
		    break;
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
  }
}
