package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class PruebaLeerAlumnosCSVIT {
	private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
	  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
	
	private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
	  driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Ignore
  public void pruebaLeerAlumnosCSV() {
	  driver.get("http://localhost:8080/ProyectoSII-war/");
	    driver.manage().window().setSize(new Dimension(767, 696));
	    driver.findElement(By.id("j_idt6:botonLeerCSV")).click();
	    driver.findElement(By.id("formLeerCSV:file")).click();
	    driver.findElement(By.id("formLeerCSV:file")).sendKeys("/home/alumno/Escritorio/Alumnos1Fila.csv");
	    driver.findElement(By.id("formLeerCSV:botonInsertar")).click();
	    driver.findElement(By.name("j_idt6:j_idt10")).click();
	    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
	    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("4"));
  }
}
