package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import es.uma.informatica.sii.anotaciones.Requisitos;

public class PruebaEncuestaIT {
	 private WebDriver driver;
	  private Map<String, Object> vars;
	  JavascriptExecutor js;
	  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
	  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
	  
	  @Before
	  public void setUp() {
		BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
	    driver = new FirefoxDriver();
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
	    driver.get("http://localhost:8080/ProyectoSII-war/");
	  }
	  @After
	  public void tearDown() {
	    driver.quit();
	  }
	  @Requisitos({"RF-14"})
	  @Test
	  public void pruebaElimEncuesta() {
		  for(int i=0;i<=2;i++) {
			  try {
				    driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				    driver.manage().window().setSize(new Dimension(694, 588));
				    driver.findElement(By.id("formIndex:botonEncuesta")).click();
				    driver.findElement(By.id("encuesta:dataTableEnc:0:BotonEliminar")).click();
				    driver.findElement(By.id("encuesta:dataTableEnc:0:BotonEliminar")).click();
				    driver.findElement(By.cssSelector("td")).click();
				    assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ninguna encuesta con esos filtros"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }

		  }

	  }
	  @Requisitos({"RF-14"})
	  @Test
	  public void pruebaVisualizarEncuesta() {
		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 592));
				  driver.findElement(By.id("formIndex:botonEncuesta")).click();
				  driver.findElement(By.id("encuesta:dataTableEnc:0:salidaFechaenEncuesta")).click();
				  assertThat(driver.findElement(By.id("encuesta:dataTableEnc:0:salidaFechaenEncuesta")).getText(), is("2016-06-04"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }

		  }

	  }
	  @Requisitos({"RF-14"})
	  @Test
	  public void pruebaBuscarMalEncuesta() {
		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 590));
				  driver.findElement(By.id("formIndex:botonEncuesta")).click();
				  driver.findElement(By.id("encuesta:dataTableEnc:globalFilter")).click();
				  driver.findElement(By.id("encuesta:dataTableEnc:globalFilter")).sendKeys("21");
				  driver.findElement(By.cssSelector("td")).click();
				  assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ninguna encuesta con esos filtros"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }
		  }
	  }
	  @Requisitos({"RF-14"})
	  @Test
	  public void pruebaBuscarEncuesta() {
		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 589));
				  driver.findElement(By.id("formIndex:botonEncuesta")).click();
				  driver.findElement(By.id("encuesta:dataTableEnc:globalFilter")).click();
				  driver.findElement(By.id("encuesta:dataTableEnc:globalFilter")).sendKeys("2016");
				  driver.findElement(By.id("encuesta:dataTableEnc:0:salidaFechaenEncuesta")).click();
				  assertThat(driver.findElement(By.id("encuesta:dataTableEnc:0:salidaFechaenEncuesta")).getText(), is("2016-06-04"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }
		  }

	  }
	  @Requisitos({"RF-14"})
	  @Test
	  public void pruebaBotonInicioEncuesta() {
		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 591));
				  driver.findElement(By.id("formIndex:botonEncuesta")).click();
				  driver.findElement(By.id("j_idt5:BtonInicioEncuesta")).click();
				  driver.findElement(By.id("texto")).click();
				  assertThat(driver.findElement(By.id("texto")).getText(), is("INICIO"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }
		  }

	  }
	  

}
