package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class PruebaindezIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
  @Before
  public void setUp() {
	BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pruebaindez() {
    driver.get("http://localhost:8080/ProyectoSII-war/");
    driver.manage().window().setSize(new Dimension(767, 694));
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.id("texto")).getText(), is("INICIO"));
    driver.findElement(By.id("formIndex:botonCentros")).click();
  }
}
