package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
public class PruebaGrupoAsigIT{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
  
  @Before
  public void setUp() {
	BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:8080/ProyectoSII-war/");
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void buscarGrupoPorAsignatura() {
    driver.get("http://localhost:8080/ProyectoSII-war/");
    driver.manage().window().setSize(new Dimension(846, 715));
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:CNombreAsig:filter")).sendKeys("Calc");
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:nombreAsig")).getText(), is("Calculo"));
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:cursoAcademic")).getText(), is("20/21"));
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("true"));
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:grupo")).getText(), is("1ºA"));
  }
  @Test
  @Ignore
  public void pruebaBuscarInventado() {
	  driver.get("http://localhost:8080/ProyectoSII-war/");
	    driver.manage().window().setSize(new Dimension(1015, 723));
	    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
	    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:CNombreAsig:filter")).click();
	    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:CNombreAsig:filter")).sendKeys("inventado");
	    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:CNombreAsig:filter")).click();
	    assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ningun grupo asignatura con esos filtros"));
}
  
  @Test
  public void editarGruporAsig() {
    driver.get("http://localhost:8080/ProyectoSII-war/");
    driver.manage().window().setSize(new Dimension(1015, 719));
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.cssSelector(".ui-icon-pencil")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:ofertaInput")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:ofertaInput")).sendKeys("false");
    driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:seleccionEditar\']/a[2]/span")).click();
    driver.findElement(By.xpath("//tbody[@id=\'gruposAsig:dataTableGrupAsig_data\']/tr/td[4]")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("false"));
  }
  @Test
  public void eliminarGrupoAsig() {
    driver.get("http://localhost:8080/ProyectoSII-war/");
    driver.manage().window().setSize(new Dimension(1015, 720));
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:BotonEliminar")).click();
    assertThat(driver.findElement(By.xpath("//tbody[@id=\'gruposAsig:dataTableGrupAsig_data\']/tr/td")).getText(), is("Ningun grupo asignatura con esos filtros"));
  }

}
