package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import es.uma.informatica.sii.anotaciones.Requisitos;

public class PruebaAlumnoIT {

	private WebDriver driver;
	  private Map<String, Object> vars;
	  JavascriptExecutor js;
	  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
	  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
	  
	  @Before
	  public void setUp() {
		BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
	    driver = new FirefoxDriver();
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
	    driver.get("http://localhost:8080/ProyectoSII-war/");
	  }
	  @After
	  public void tearDown() {
	    driver.quit();
	  }
	  
	  @Requisitos({"RF-05"})
	  @Test
	  public void buscarAlumnoTest() {



		  for(int i=0;i<=2;i++) {
			  try {

				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(1796, 836));
				  driver.findElement(By.id("formIndex:botonAlumnos")).click();
				  driver.findElement(By.id("alumno:dataTableGrupAsig:globalFilter")).click();
				  driver.findElement(By.id("alumno:dataTableGrupAsig:globalFilter")).sendKeys("Molina");
				  driver.findElement(By.id("alumno:dataTableGrupAsig:0:primerapellido")).click();
				  assertThat(driver.findElement(By.id("alumno:dataTableGrupAsig:0:primerapellido")).getText(), is("Molina"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }
		  }

	  }
	  
	  @Requisitos({"RF-05"})
	  @Test
	  public void pruebaBuscarMalTest() {

		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				    driver.manage().window().setSize(new Dimension(967, 789));
				    driver.findElement(By.id("formIndex:botonAlumnos")).click();
				    driver.findElement(By.id("alumno:dataTableGrupAsig:globalFilter")).click();
				    driver.findElement(By.id("alumno:dataTableGrupAsig:globalFilter")).sendKeys("HOLA");
				    driver.findElement(By.cssSelector("td")).click();
				    assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ningun alumno con esos filtros"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }  
		  }

	  }
	  
	  @Requisitos({"RF-05"})
	  @Test
	  public void pruebaModificarAlumnoTest() {

		  for(int i=0;i<=2;i++)  {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(967, 793));
				  driver.findElement(By.id("formIndex:botonAlumnos")).click();
				  driver.findElement(By.cssSelector(".ui-icon-pencil")).click();
				  driver.findElement(By.id("alumno:dataTableGrupAsig:0:nombreinput")).sendKeys("Graciasmodificadooo");
				  driver.findElement(By.cssSelector(".ui-icon-check")).click();
				  driver.findElement(By.id("alumno:dataTableGrupAsig:0:nombre")).click();
				  assertThat(driver.findElement(By.id("alumno:dataTableGrupAsig:0:nombre")).getText(), is("Graciasmodificadooo"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }
		  }
	  }
	  
	  @Requisitos({"RF-05"})
	  @Test
	  public void pruebaEliminarAlumnoTest() {


		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(967, 796));
				  driver.findElement(By.id("formIndex:botonAlumnos")).click();
				  driver.findElement(By.id("alumno:dataTableGrupAsig:0:BotonEliminar")).click();
				  driver.findElement(By.id("formIndex:botonAlumnos")).click();
				  assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ningun alumno con esos filtros"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }
		  }


	  }

	
}
