package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
public class PruebaGrupoAsigIT{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
  
  @Before
  public void setUp() {
	BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:8080/ProyectoSII-war/");
    insertarDatosNecesarios();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  private void crearCentro() {
	    driver.findElement(By.id("formIndex:botonCentros")).click();
	    driver.findElement(By.id("Centros:BotonCrear")).click();
	    driver.findElement(By.id("centro:nombre")).click();
	    driver.findElement(By.id("centro:nombre")).sendKeys("ETSi");
	    driver.findElement(By.id("centro:direccion")).click();
	    driver.findElement(By.id("centro:direccion")).sendKeys("Teatin");
	    driver.findElement(By.id("centro:telefono")).click();
	    driver.findElement(By.id("centro:telefono")).sendKeys("6");
	    driver.findElement(By.id("centro:BotonAccion")).click();
  }
  private void crearGrupo() {
	  
  }
  private void insertarDatosNecesarios() {
	  crearCentro();
	  //TITULACIONES 
	  driver.findElement(By.id("formIndex:botonLeerCSV")).click();
	    driver.findElement(By.id("formLeerCSV:selectorImportacion")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("formLeerCSV:selectorImportacion"));
	      dropdown.findElement(By.xpath("//option[. = 'Titulacion']")).click();
	    }
	    driver.findElement(By.xpath("//select[@id=\'formLeerCSV:selectorImportacion\']/option[2]")).click();
	    driver.findElement(By.id("formLeerCSV:file")).sendKeys("/home/alumno/Escritorio/Titulacion.csv");
	    driver.findElement(By.id("formLeerCSV:botonInsertar")).click();
	   //ASIGNATURAS
	    driver.findElement(By.id("formIndex:botonLeerCSV")).click();
	    driver.findElement(By.id("formLeerCSV:selectorImportacion")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("formLeerCSV:selectorImportacion"));
	      dropdown.findElement(By.xpath("//option[. = 'Asignatura']")).click();
	    }
	    driver.findElement(By.xpath("//option[@value=\'as\']")).click();
	    driver.findElement(By.id("formLeerCSV:file")).sendKeys("/home/alumno/Escritorio/Oferta-asignaturas.csv");
	    driver.findElement(By.id("formLeerCSV:botonInsertar")).click();
	   crearGrupo();
  }
  
  @Test
  @Ignore
  public void grupoAsigITLista() {
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.xpath("//tbody[@id=\'gruposAsig:dataTableGrupAsig_data\']/tr/td")).click();
    assertThat(driver.findElement(By.cssSelector(".ui-widget-content:nth-child(1) > td:nth-child(1)")).getText(), is("1ºA"));
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:nombreAsig")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:nombreAsig")).getText(), is("Calculo"));
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:cursoAcademic")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:cursoAcademic")).getText(), is("20/21"));
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("true"));
  }
  @Test
  @Ignore
  public void editarGrupoAsigIT() {
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:oferta")).getText(), is("true"));
    driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:seleccionEditar\']/a/span")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:modelInput")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:modelInput")).sendKeys("false");
    driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:seleccionEditar\']/a[2]")).click();
    driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:j_idt11\']/div")).click();
    assertThat(driver.findElement(By.xpath("//div[@id=\'gruposAsig:dataTableGrupAsig:0:j_idt11\']/div")).getText(), is("false"));
  }
  
  @Test
  @Ignore
  public void buscadorPorAsignatura() {
    driver.findElement(By.id("formIndex:botonGrupoAsig")).click();
    driver.findElement(By.xpath("//tbody[@id=\'gruposAsig:dataTableGrupAsig_data\']/tr/td[2]")).click();
    assertThat(driver.findElement(By.id("gruposAsig:dataTableGrupAsig:0:nombreAsig")).getText(), is("Cálculo para la Computación"));
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:j_idt8:filter")).click();
    driver.findElement(By.id("gruposAsig:dataTableGrupAsig:j_idt8:filter")).sendKeys("Cálculo");
  }
}
