package NeuBDProyectoSIITests;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import es.uma.informatica.sii.anotaciones.Requisitos;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class PruebaAsignaturaIT {

	
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
	private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
	@Before
	public void setUp() {

		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	  
	  
	  
	  
	  
	  
	//Para los tets hemos tenido que usar una estructura de un for junto con un try catch ya que algunas veces saltaba la excepcion StaleElementReferenceException 
    //y otras veces no. Hemos visto aqui https://www.softwaretestingmaterial.com/stale-element-reference-exception-selenium-webdriver/
    //que se soluciona asi.
	
	@Test
	@Requisitos({"RF-04"})
	public void bUscarAsignatura() {

		for(int i=0; i<=2;i++){
			try{
				driver.navigate().refresh();
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(2139, 922));
				driver.findElement(By.id("formIndex:botonAsignaturas")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:globalFilter")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:globalFilter")).sendKeys("311");
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:0:ACodigo")).click();
				assertThat(driver.findElement(By.id("Asignaturas:TablaAsignaturas:0:ACodigo")).getText(), is("311"));

				break;
			}
			catch(Exception e){

			}
		}

	}



	@Test
	@Requisitos({"RF-04"})
	public void pruebaBuscarAsignaturaMAL() {


		for(int i=0; i<=2;i++){
			try{
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(2139, 924));
				driver.findElement(By.id("formIndex:botonAsignaturas")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:globalFilter")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:globalFilter")).sendKeys("minecraft");
				driver.navigate().refresh();
				driver.findElement(By.cssSelector("td")).click();
				assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ninguna asignatura con esos filtros"));
				break;
			}
			catch(Exception e){
			}
		}


	}	


	@Test
	@Requisitos({"RF-04"})
	public void pruebaBorrarAsignatura() {

		for(int i=0; i<=2;i++){
			try{
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(2139, 887));
				driver.findElement(By.id("formIndex:botonAsignaturas")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:0:BotonEliminarA")).click();
				driver.findElement(By.id("formIndex:botonAsignaturas")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:globalFilter")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:globalFilter")).sendKeys("290");
				driver.findElement(By.cssSelector("td")).click();
				assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ninguna asignatura con esos filtros"));
				break;
			}
			catch(Exception e){
			}
		}

	}

	@Test
	@Requisitos({"RF-04"})
	public void pruebaModificarAsignatura() {

		for(int i=0; i<=2;i++){
			try{
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(2139, 888));
				driver.findElement(By.id("formIndex:botonAsignaturas")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:0:BotonModificarA")).click();
				driver.findElement(By.id("Asignatura:nombre")).click();
				driver.findElement(By.id("Asignatura:nombre")).sendKeys("modificado");
				driver.findElement(By.id("Asignatura:boton_asignatura_accion")).click();
				driver.findElement(By.id("Asignatura:boton_volver_edicionA")).click();
				driver.findElement(By.id("Asignaturas:TablaAsignaturas:0:Anombre")).click();
				assertThat(driver.findElement(By.id("Asignaturas:TablaAsignaturas:0:Anombre")).getText(), is("Calculomodificado"));
				break;
			}
			catch(Exception e){
			}
		}




	}


	@Test
	@Requisitos({"RF-04"})
	public void pruebaVerOptativasAsignaturas() {


		for(int i=0; i<=2;i++){
			try{
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(2139, 889));
				driver.findElement(By.id("formIndex:botonAsignaturas")).click();
				driver.findElement(By.id("Asignaturas:botonOptativasA")).click();
				driver.findElement(By.cssSelector(".p-d-flex > span")).click();
				assertThat(driver.findElement(By.cssSelector(".p-d-flex > span")).getText(), is("Lista de Optativas"));
				break;
			}
			catch(Exception e){
			}
		}


	}

	@Test
	@Requisitos({"RF-04"})
	public void pruebaBotonInicio() {



		for(int i=0; i<=2;i++){
			try{
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(2139, 890));
				driver.findElement(By.id("formIndex:botonAsignaturas")).click();
				driver.findElement(By.id("Asignaturas:botonIndiceA")).click();
				driver.findElement(By.id("texto")).click();
				assertThat(driver.findElement(By.id("texto")).getText(), is("INICIO"));
				break;
			}
			catch(Exception e){
			}
		}  




	}
	
	
	  
	  
}
