package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import es.uma.informatica.sii.anotaciones.Requisitos;

public class PruebaAsigMatriIT {
	  private WebDriver driver;
	  private Map<String, Object> vars;
	  JavascriptExecutor js;
	  private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
	  private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";
	  
	  @Before
	  public void setUp() {
		BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
	    driver = new FirefoxDriver();
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
	    driver.get("http://localhost:8080/ProyectoSII-war/");
	  }
	  @After
	  public void tearDown() {
	    driver.quit();
	  }
	  
	  @Requisitos({"RF-17"})
	  @Test
	  public void modiAsigMatriTest() {
		  for(int i=0;i<=4;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 597));
				  driver.findElement(By.id("formIndex:botonAsigMatri")).click();
				  driver.findElement(By.id("asig_matri:asigsMatri:Asignatura:filter")).click();
				  driver.findElement(By.id("asig_matri:asigsMatri:Asignatura:filter")).sendKeys("Ca");
				  driver.findElement(By.cssSelector(".ui-icon-pencil")).click();
				  driver.findElement(By.id("asig_matri:asigsMatri:0:modelInputIdioma")).click();
				  driver.findElement(By.id("asig_matri:asigsMatri:0:modelInputIdioma")).sendKeys("true");
				  driver.findElement(By.cssSelector(".ui-icon-check")).click();
				  driver.findElement(By.id("asig_matri:asigsMatri:0:salidaIdioma")).click();
				  driver.findElement(By.id("asig_matri:asigsMatri:0:salidaIdioma")).click();
				  assertThat(driver.findElement(By.id("asig_matri:asigsMatri:0:salidaIdioma")).getText(), is("true"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }

		  }
	  }
	  @Requisitos({"RF-17"})
	  @Test
	  public void pruebaBuscarMalAsigMatri() {
		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 587));
				  driver.findElement(By.id("formIndex:botonAsigMatri")).click();
				  driver.findElement(By.id("asig_matri:j_idt6:globalFilter")).click();
				  driver.findElement(By.id("asig_matri:j_idt6:globalFilter")).sendKeys("Maincra");
				  driver.findElement(By.cssSelector("td")).click();
				  assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ningun asignatura matricula con esos filtros"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }

		  }
	  }
	  @Test
	  @Requisitos({"RF-17"})
	  public void pruebaBuscarAsigMatri() {

		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 586));
				  driver.findElement(By.id("formIndex:botonAsigMatri")).click();
				  driver.findElement(By.id("asig_matri:j_idt6:globalFilter")).click();
				  driver.findElement(By.id("asig_matri:j_idt6:globalFilter")).sendKeys("Calculo");
				  driver.findElement(By.id("asig_matri:j_idt6:0:salidaAsignatura")).click();
				  assertThat(driver.findElement(By.id("asig_matri:j_idt6:0:salidaAsignatura")).getText(), is("Calculo"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }

		  }
	  }
	  
	  @Requisitos({"RF-17"})
	  @Test
	  public void pruebaBotonVolverAsigMatri() {
		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 585));
				  driver.findElement(By.id("formIndex:botonAsigMatri")).click();
				  driver.findElement(By.id("j_idt5:btonVolverAsig")).click();
				  driver.findElement(By.id("texto")).click();
				  assertThat(driver.findElement(By.id("texto")).getText(), is("INICIO"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }

		  }

	  }
	  @Requisitos({"RF-17"})
	  @Test
	  public void pruebaVisualizarAsigMatri() {
		  for(int i=0;i<=2;i++) {
			  try {
				  driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				  driver.manage().window().setSize(new Dimension(694, 594));
				  driver.findElement(By.id("formIndex:botonAsigMatri")).click();
				  driver.findElement(By.id("asig_matri:j_idt6:0:salidaAsignatura")).click();
				  assertThat(driver.findElement(By.id("asig_matri:j_idt6:0:salidaAsignatura")).getText(), is("Calculo"));
				  break;
			  } catch (Exception e) {
				  // TODO: handle exception
			  }
		  }
	  }
	  
}

