package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
public class PruebaLeerCSVIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Ignore
  public void pruebaLeerCSV() {
	    driver.get("http://localhost:8080/ProyectoSII-war/");
	    driver.manage().window().setSize(new Dimension(767, 692));
	    driver.findElement(By.id("j_idt6:botonLeerCSV")).click();
	    driver.findElement(By.id("formLeerCSV:selectorImportacion")).click();
	    driver.findElement(By.cssSelector(".ui-state-hover:nth-child(4)")).click();
	    driver.findElement(By.id("formLeerCSV:selectorImportacion_1")).click();
	    driver.findElement(By.id("formLeerCSV:file")).click();
    driver.findElement(By.id("formLeerCSV:file")).sendKeys("/home/alumno/Escritorio/Titulacion.csv");
    driver.findElement(By.id("formLeerCSV:botonInsertar")).click();
    driver.findElement(By.name("j_idt6:j_idt7")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("1041"));
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("Grado en Ingeniería Informática"));
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(3)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(3)")).getText(), is("240"));
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(1)")).getText(), is("1073"));
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(2)")).getText(), is("Doble Grado en Ingeniería Informatica y Matemáticas"));
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(3)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(3)")).getText(), is("372"));
  }
  
  @Test
  public void pruebaInsertarTiulaciones(){
	  driver.get("http://localhost:8080/ProyectoSII-war/");
	    driver.manage().window().setSize(new Dimension(767, 699));
	    driver.findElement(By.id("j_idt6:botonLeerCSV")).click();
	    driver.findElement(By.id("formLeerCSV:selectorImportacion")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("formLeerCSV:selectorImportacion"));
	      dropdown.findElement(By.xpath("//option[. = 'Titulacion']")).click();
	    }
	    driver.findElement(By.xpath("//select[@id=\'formLeerCSV:selectorImportacion\']/option[2]")).click();
	    driver.findElement(By.id("formLeerCSV:file")).click();
	    driver.findElement(By.id("formLeerCSV:file")).sendKeys("/home/alumno/Escritorio/Titulacion.csv");
	    driver.findElement(By.id("formLeerCSV:botonInsertar")).click(); 
	    driver.findElement(By.name("j_idt6:j_idt7")).click();
	    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
	    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("1041"));
	    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
	    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
	    {
	      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)"));
	      Actions builder = new Actions(driver);
	      builder.doubleClick(element).perform();
	    }
	    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
	    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("Grado en Ingeniería Informática"));
	    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(3)")).click();
	    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(3)")).getText(), is("240"));
	    driver.findElement(By.id("j_idt6:botonLeerCSV")).click();
  }
}
