package NeuBDProyectoSIITests;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import es.uma.informatica.sii.anotaciones.Requisitos;

public class PruebaTitulacionIT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	private static final String UNIDAD_PERSISTENCIA = "ProyectoPU";
	private static final String CONTEXT_ROOT = "http://localhost:8080/ProyectoSII-war/";

	@Before
	public void setUp() {
		BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA);
		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		driver.get("http://localhost:8080/ProyectoSII-war/");
	}
	@After
	public void tearDown() {
		driver.quit();
	}

	//Para los tets hemos tenido que usar una estructura de un for junto con un try catch ya que algunas veces saltaba la excepcion StaleElementReferenceException 
	//y otras veces no. Hemos visto aqui https://www.softwaretestingmaterial.com/stale-element-reference-exception-selenium-webdriver/
	//que se soluciona asi.	
	@Requisitos({"RF-06"})
	@Test
	public void modificarTitulacionTest() {
		for(int i=0; i<=2;i++){
			try{
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(825, 720));
				driver.findElement(By.id("formIndex:botonTitulaciones")).click();
				driver.findElement(By.id("Titulaciones:TablaTitulacion:0:BotonModificar")).click();
				driver.findElement(By.id("titulacion:nombre")).click();
				driver.findElement(By.id("titulacion:nombre")).sendKeys("Modificada");
				driver.findElement(By.id("titulacion:BotonAccion")).click();
				driver.findElement(By.id("titulacion:BotonCancelar")).click();
				assertThat(driver.findElement(By.id("Titulaciones:TablaTitulacion:0:SalidaNombre")).getText(), is("InformaticaModificada"));


				break;
			}
			catch(Exception e){

			}
		}

	}



	//Para los tets hemos tenido que usar una estructura de un for junto con un try catch ya que algunas veces saltaba la excepcion StaleElementReferenceException 
	//y otras veces no. Hemos visto aqui https://www.softwaretestingmaterial.com/stale-element-reference-exception-selenium-webdriver/
	//que se soluciona asi.
	@Requisitos({"RF-06"})
	@Test
	public void buscarTitulacionTest() {

		for(int i=0; i<=2;i++){
			try{
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(825, 722));
				driver.findElement(By.id("formIndex:botonTitulaciones")).click();
				driver.findElement(By.id("Titulaciones:TablaTitulacion:globalFilter")).click();
				driver.findElement(By.id("Titulaciones:TablaTitulacion:globalFilter")).sendKeys("66");
				driver.findElement(By.id("Titulaciones:TablaTitulacion:0:SalidaCodigo")).click();
				assertThat(driver.findElement(By.id("Titulaciones:TablaTitulacion:0:SalidaCodigo")).getText(), is("66"));


				break;
			}
			catch(Exception e){

			}
		}

	}




	//Para los tets hemos tenido que usar una estructura de un for junto con un try catch ya que algunas veces saltaba la excepcion StaleElementReferenceException 
	//y otras veces no. Hemos visto aqui https://www.softwaretestingmaterial.com/stale-element-reference-exception-selenium-webdriver/
	//que se soluciona asi.
	@Requisitos({"RF-06"})
	@Test
	public void buscarTitulacionMalTest() {
		for(int i=0; i<=2;i++){
			try{
				driver.get("http://0.0.0.0:8080/ProyectoSII-war/");
				driver.manage().window().setSize(new Dimension(825, 723));
				driver.findElement(By.id("formIndex:botonTitulaciones")).click();
				driver.findElement(By.id("Titulaciones:TablaTitulacion:globalFilter")).click();
				driver.findElement(By.id("Titulaciones:TablaTitulacion:globalFilter")).sendKeys("67");
				driver.findElement(By.cssSelector("td")).click();
				assertThat(driver.findElement(By.cssSelector("td")).getText(), is("Ninguna titulacion con esos filtros"));


				break;
			}
			catch(Exception e){

			}
		}

	}




}
